// Internal catalog used to audit DIS v7 source coverage.
using OpenDisNet.Protocol;

namespace OpenDisNet.Internal;

internal static class Dis7SchemaManifest
{
    public const int ClassCount = 233;
    public const int PduCount = 72;
    private static readonly DisPduDescriptor[] Entries =
    [
        new(1, "EntityStatePdu", "EntityInformationFamilyPdus.xml"),
        new(2, "FirePdu", "WarfareFamilyPdus.xml"),
        new(3, "DetonationPdu", "WarfareFamilyPdus.xml"),
        new(4, "CollisionPdu", "EntityInformationFamilyPdus.xml"),
        new(5, "ServiceRequestPdu", "LogisticsFamilyPdus.xml"),
        new(6, "ResupplyOfferPdu", "LogisticsFamilyPdus.xml"),
        new(7, "ResupplyReceivedPdu", "LogisticsFamilyPdus.xml"),
        new(8, "ResupplyCancelPdu", "LogisticsFamilyPdus.xml"),
        new(9, "RepairCompletePdu", "LogisticsFamilyPdus.xml"),
        new(10, "RepairResponsePdu", "LogisticsFamilyPdus.xml"),
        new(11, "CreateEntityPdu", "SimulationManagementFamilyPdus.xml"),
        new(12, "RemoveEntityPdu", "SimulationManagementFamilyPdus.xml"),
        new(13, "StartResumePdu", "SimulationManagementFamilyPdus.xml"),
        new(14, "StopFreezePdu", "SimulationManagementFamilyPdus.xml"),
        new(15, "AcknowledgePdu", "SimulationManagementFamilyPdus.xml"),
        new(16, "ActionRequestPdu", "SimulationManagementFamilyPdus.xml"),
        new(17, "ActionResponsePdu", "SimulationManagementFamilyPdus.xml"),
        new(18, "DataQueryPdu", "SimulationManagementFamilyPdus.xml"),
        new(19, "SetDataPdu", "SimulationManagementFamilyPdus.xml"),
        new(20, "DataPdu", "SimulationManagementFamilyPdus.xml"),
        new(21, "EventReportPdu", "SimulationManagementFamilyPdus.xml"),
        new(22, "CommentPdu", "SimulationManagementFamilyPdus.xml"),
        new(23, "ElectromagneticEmissionPdu", "DistributedEmissionsFamilyPdus.xml"),
        new(24, "DesignatorPdu", "DistributedEmissionsFamilyPdus.xml"),
        new(25, "TransmitterPdu", "RadioCommunicationsFamilyPdus.xml"),
        new(26, "SignalPdu", "RadioCommunicationsFamilyPdus.xml"),
        new(27, "ReceiverPdu", "RadioCommunicationsFamilyPdus.xml"),
        new(28, "IdentificationFriendOrFoePdu", "DistributedEmissionsFamilyPdus.xml"),
        new(29, "UnderwaterAcousticPdu", "DistributedEmissionsFamilyPdus.xml"),
        new(30, "SupplementalEmissionEntityStatePdu", "DistributedEmissionsFamilyPdus.xml"),
        new(31, "IntercomSignalPdu", "RadioCommunicationsFamilyPdus.xml"),
        new(32, "IntercomControlPdu", "RadioCommunicationsFamilyPdus.xml"),
        new(33, "AggregateStatePdu", "EntityManagementFamilyPdus.xml"),
        new(34, "IsGroupOfPdu", "EntityManagementFamilyPdus.xml"),
        new(35, "TransferOwnershipPdu", "EntityManagementFamilyPdus.xml"),
        new(36, "IsPartOfPdu", "EntityManagementFamilyPdus.xml"),
        new(37, "MinefieldStatePdu", "MinefieldFamilyPdus.xml"),
        new(38, "MinefieldQueryPdu", "MinefieldFamilyPdus.xml"),
        new(39, "MinefieldDataPdu", "MinefieldFamilyPdus.xml"),
        new(40, "MinefieldResponseNACKPdu", "MinefieldFamilyPdus.xml"),
        new(41, "EnvironmentalProcessPdu", "SyntheticEnvironmentFamilyPdus.xml"),
        new(42, "GriddedDataPdu", "SyntheticEnvironmentFamilyPdus.xml"),
        new(43, "PointObjectStatePdu", "SyntheticEnvironmentFamilyPdus.xml"),
        new(44, "LinearObjectStatePdu", "SyntheticEnvironmentFamilyPdus.xml"),
        new(45, "ArealObjectStatePdu", "SyntheticEnvironmentFamilyPdus.xml"),
        new(46, "TimeSpacePositionInformationPdu", "LiveEntityFamilyPdus.xml"),
        new(47, "AppearancePdu", "LiveEntityFamilyPdus.xml"),
        new(48, "ArticulatedPartsPdu", "LiveEntityFamilyPdus.xml"),
        new(49, "LiveEntityFirePdu", "LiveEntityFamilyPdus.xml"),
        new(50, "LiveEntityDetonationPdu", "LiveEntityFamilyPdus.xml"),
        new(51, "CreateEntityReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(52, "RemoveEntityReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(53, "StartResumeReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(54, "StopFreezeReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(55, "AcknowledgeReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(56, "ActionRequestReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(57, "ActionResponseReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(58, "DataQueryReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(59, "SetDataReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(60, "DataReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(61, "EventReportReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(62, "CommentReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(63, "RecordReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(64, "SetRecordReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(65, "RecordQueryReliablePdu", "SimulationManagementWithReliabilityFamilyPdus.xml"),
        new(66, "CollisionElasticPdu", "EntityInformationFamilyPdus.xml"),
        new(67, "EntityStateUpdatePdu", "EntityInformationFamilyPdus.xml"),
        new(68, "DirectedEnergyFirePdu", "WarfareFamilyPdus.xml"),
        new(69, "EntityDamageStatusPdu", "WarfareFamilyPdus.xml"),
        new(70, "InformationOperationsActionPdu", "InformationOperationsFamilyPdus.xml"),
        new(71, "InformationOperationsReportPdu", "InformationOperationsFamilyPdus.xml"),
        new(72, "AttributePdu", "EntityInformationFamilyPdus.xml"),
    ];

    public static ReadOnlySpan<DisPduDescriptor> Pdus => Entries;
}
