// DIS v7 protocol models reviewed from EntityInformationFamilyPdus.xml.
#pragma warning disable CS0108
namespace OpenDisNet.Pdus;

/// <summary>
/// 7.2.6. Information about individual attributes for a particular entity, other object, or event may be communicated using an Attribute PDU. The Attribute PDU shall not be used to exchange data available in any other PDU except where explicitly mentioned in the PDU issuance instructions within this standard. See 5.3.6.
/// </summary>
public partial class AttributePdu : EntityInformationInteractionFamilyPdu
{
    /// <summary>
    /// This field shall identify the simulation issuing the Attribute PDU. It shall be represented by a Simulation Address record (see 6.2.79).
    /// </summary>
    public SimulationAddress OriginatingSimulationAddress { get; set; } = new SimulationAddress();

    /// <summary>
    /// Padding
    /// </summary>
    public int Padding1 { get; set; }

    /// <summary>
    /// Padding
    /// </summary>
    public short Padding2 { get; set; }

    /// <summary>
    /// This field shall represent the type of the PDU that is being extended or updated, if applicable. It shall be represented by an 8-bit enumeration.
    /// </summary>
    public byte AttributeRecordPduType { get; set; }

    /// <summary>
    /// This field shall indicate the Protocol Version associated with the Attribute Record PDU Type. It shall be represented by an 8-bit enumeration.
    /// </summary>
    public byte AttributeRecordProtocolVersion { get; set; }

    /// <summary>
    /// This field shall contain the Attribute record type of the Attribute records in the PDU if they all have the same Attribute record type. It shall be represented by a 32-bit enumeration.
    /// </summary>
    public uint MasterAttributeRecordType { get; set; }

    /// <summary>
    /// This field shall identify the action code applicable to this Attribute PDU. The Action Code shall apply to all Attribute records contained in the PDU. It shall be represented by an 8-bit enumeration.
    /// </summary>
    public byte ActionCode { get; set; }

    /// <summary>
    /// Padding
    /// </summary>
    public byte Padding3 { get; set; }

    /// <summary>
    /// This field shall specify the number of Attribute Record Sets that make up the remainder of the PDU. It shall be represented by a 16-bit unsigned integer.
    /// </summary>
    internal ushort NumberAttributeRecordSet { get; set; }

    public List<AttributeRecordSet> AttributeRecordSets { get; set; } = [];

}

/// <summary>
/// Each Attribute Record Set shall contain the following information: the Entity or Object ID to which all Attribute records in the set apply, plus one or more Attribute records
/// </summary>
public partial class AttributeRecordSet
{
    public EntityID EntityId { get; set; } = new EntityID();

    internal ushort NumberOfAttributeRecords { get; set; }

    public List<Attribute> AttributeRecords { get; set; } = [];

}

/// <summary>
/// 7.2.4 Information about elastic collisions in a DIS exercise shall be communicated using a Collision-Elastic PDU. See 5.3.4.
/// </summary>
public partial class CollisionElasticPdu : EntityInformationInteractionFamilyPdu
{
    /// <summary>
    /// This field shall identify the entity that is issuing the PDU and shall be represented by an Entity Identifier record (see 6.2.28)
    /// </summary>
    public EntityID IssuingEntityId { get; set; } = new EntityID();

    /// <summary>
    /// This field shall identify the entity that has collided with the issuing entity. This field shall be a valid identifier of an entity or server capable of responding to the receipt of this Collision-Elastic PDU. This field shall be represented by an Entity Identifier record (see 6.2.28).
    /// </summary>
    public EntityID CollidingEntityId { get; set; } = new EntityID();

    /// <summary>
    /// This field shall contain an identification generated by the issuing simulation application to associate related collision events. This field shall be represented by an Event Identifier record (see 6.2.34).
    /// </summary>
    public EventIdentifier CollisionEventId { get; set; } = new EventIdentifier();

    /// <summary>
    /// some padding
    /// </summary>
    public ushort Pad { get; set; }

    /// <summary>
    /// This field shall contain the velocity at the time the collision is detected at the point the collision is detected. The velocity shall be represented in world coordinates. This field shall be represented by the Linear Velocity Vector record [see 6.2.95 item c)]
    /// </summary>
    public Vector3Float ContactVelocity { get; set; } = new Vector3Float();

    /// <summary>
    /// This field shall contain the mass of the issuing entity and shall be represented by a 32-bit floating point number representing kilograms
    /// </summary>
    public float Mass { get; set; }

    /// <summary>
    /// This field shall specify the location of the collision with respect to the entity with which the issuing entity collided. This field shall be represented by an Entity Coordinate Vector record [see 6.2.95 item a)].
    /// </summary>
    public Vector3Float LocationOfImpact { get; set; } = new Vector3Float();

    /// <summary>
    /// These six records represent the six independent components of a positive semi-definite matrix formed by pre-multiplying and post-multiplying the tensor of inertia, by the anti-symmetric matrix generated by the moment arm, and shall be represented by 32-bit floating point numbers (see 5.3.4.4)
    /// </summary>
    public float CollisionIntermediateResultXX { get; set; }

    /// <summary>
    /// tensor values
    /// </summary>
    public float CollisionIntermediateResultXY { get; set; }

    /// <summary>
    /// tensor values
    /// </summary>
    public float CollisionIntermediateResultXZ { get; set; }

    /// <summary>
    /// tensor values
    /// </summary>
    public float CollisionIntermediateResultYY { get; set; }

    /// <summary>
    /// tensor values
    /// </summary>
    public float CollisionIntermediateResultYZ { get; set; }

    /// <summary>
    /// tensor values
    /// </summary>
    public float CollisionIntermediateResultZZ { get; set; }

    /// <summary>
    /// This record shall represent the normal vector to the surface at the point of collision detection. The surface normal shall be represented in world coordinates. This field shall be represented by an Entity Coordinate Vector record [see 6.2.95 item a)].
    /// </summary>
    public Vector3Float UnitSurfaceNormal { get; set; } = new Vector3Float();

    /// <summary>
    /// This field shall represent the degree to which energy is conserved in a collision and shall be represented by a 32-bit floating point number. In addition, it represents a free parameter by which simulation application developers may "tune" their collision interactions.
    /// </summary>
    public float CoefficientOfRestitution { get; set; }

}

/// <summary>
/// 7.2.3 Collisions between entities shall be communicated by issuing a Collision PDU. See 5.3.3.
/// </summary>
public partial class CollisionPdu : EntityInformationInteractionFamilyPdu
{
    /// <summary>
    /// This field shall identify the entity that is issuing the PDU, and shall be represented by an Entity Identifier record (see 6.2.28).
    /// </summary>
    public EntityID IssuingEntityId { get; set; } = new EntityID();

    /// <summary>
    /// This field shall identify the entity that has collided with the issuing entity (see 5.3.3.4). This field shall be represented by an Entity Identifier record (see 6.2.28).
    /// </summary>
    public EntityID CollidingEntityId { get; set; } = new EntityID();

    /// <summary>
    /// This field shall contain an identification generated by the issuing simulation application to associate related collision events. This field shall be represented by an Event Identifier record (see 6.2.34).
    /// </summary>
    public EventIdentifier EventId { get; set; } = new EventIdentifier();

    /// <summary>
    /// This field shall identify the type of collision. The Collision Type field shall be represented by an 8-bit record of enumerations
    /// </summary>
    public byte CollisionType { get; set; }

    /// <summary>
    /// some padding
    /// </summary>
    public byte Pad { get; set; }

    /// <summary>
    /// This field shall contain the velocity (at the time the collision is detected) of the issuing entity. The velocity shall be represented in world coordinates. This field shall be represented by the Linear Velocity Vector record [see 6.2.95 item c)].
    /// </summary>
    public Vector3Float Velocity { get; set; } = new Vector3Float();

    /// <summary>
    /// This field shall contain the mass of the issuing entity, and shall be represented by a 32-bit floating point number representing kilograms.
    /// </summary>
    public float Mass { get; set; }

    /// <summary>
    /// This field shall specify the location of the collision with respect to the entity with which the issuing entity collided. The Location field shall be represented by an Entity Coordinate Vector record [see 6.2.95 item a)].
    /// </summary>
    public Vector3Float Location { get; set; } = new Vector3Float();

}

/// <summary>
/// Section 5.3.3. Common superclass for EntityState, Collision, collision-elastic, and entity state update PDUs.
/// </summary>
public abstract partial class EntityInformationInteractionFamilyPdu : PduBase
{
}

/// <summary>
/// 7.2.2. Represents the position and state of one entity in the world. See 5.3.2.
/// </summary>
public partial class EntityStatePdu : EntityInformationInteractionFamilyPdu
{
    /// <summary>
    /// Unique ID for an entity that is tied to this state information
    /// </summary>
    public EntityID EntityId { get; set; } = new EntityID();

    /// <summary>
    /// What force this entity is affiliated with, eg red, blue, neutral, etc
    /// </summary>
    public byte ForceId { get; set; }

    /// <summary>
    /// How many variable parameters are in the variable length list. In earlier versions of DIS these were known as articulation parameters
    /// </summary>
    internal byte NumberOfVariableParameters { get; set; }

    /// <summary>
    /// Describes the type of entity in the world
    /// </summary>
    public EntityType EntityType { get; set; } = new EntityType();

    public EntityType AlternativeEntityType { get; set; } = new EntityType();

    /// <summary>
    /// Describes the speed of the entity in the world
    /// </summary>
    public Vector3Float EntityLinearVelocity { get; set; } = new Vector3Float();

    /// <summary>
    /// describes the location of the entity in the world
    /// </summary>
    public Vector3Double EntityLocation { get; set; } = new Vector3Double();

    /// <summary>
    /// describes the orientation of the entity, in euler angles with units of radians
    /// </summary>
    public EulerAngles EntityOrientation { get; set; } = new EulerAngles();

    /// <summary>
    /// a series of bit flags that are used to help draw the entity, such as smoking, on fire, etc.
    /// </summary>
    public uint EntityAppearance { get; set; }

    /// <summary>
    /// parameters used for dead reckoning
    /// </summary>
    public DeadReckoningParameters DeadReckoningParameters { get; set; } = new DeadReckoningParameters();

    /// <summary>
    /// 11 characters that can be used for entity identification, debugging, or to draw unique strings on the side of entities in the world
    /// </summary>
    public EntityMarking Marking { get; set; } = new EntityMarking();

    /// <summary>
    /// a series of bit flags
    /// </summary>
    public uint Capabilities { get; set; }

    /// <summary>
    /// variable length list of variable parameters. In earlier DIS versions this was articulation parameters.
    /// </summary>
    public List<VariableParameter> VariableParameters { get; set; } = [];

}

/// <summary>
/// 7.2.5. Nonstatic information about a particular entity may be communicated by issuing an Entity State Update PDU. 5.3.5.
/// </summary>
public partial class EntityStateUpdatePdu : EntityInformationInteractionFamilyPdu
{
    /// <summary>
    /// This field shall identify the entity issuing the PDU, and shall be represented by an Entity Identifier record (see 6.2.28).
    /// </summary>
    public EntityID EntityId { get; set; } = new EntityID();

    /// <summary>
    /// Padding
    /// </summary>
    public byte Padding1 { get; set; }

    /// <summary>
    /// This field shall specify the number of variable parameters present. This field shall be represented by an 8-bit unsigned integer (see Annex I).
    /// </summary>
    internal byte NumberOfVariableParameters { get; set; }

    /// <summary>
    /// This field shall specify an entity's linear velocity. The coordinate system for an entity's linear velocity depends on the dead reckoning algorithm used. This field shall be represented by a Linear Velocity Vector record [see 6.2.95 item c)]).
    /// </summary>
    public Vector3Float EntityLinearVelocity { get; set; } = new Vector3Float();

    /// <summary>
    /// This field shall specify an entity's physical location in the simulated world and shall be represented by a World Coordinates record (see 6.2.97).
    /// </summary>
    public Vector3Double EntityLocation { get; set; } = new Vector3Double();

    /// <summary>
    /// This field shall specify an entity's orientation with units of radians and shall be represented by an Euler Angles record (see 6.2.33).
    /// </summary>
    public EulerAngles EntityOrientation { get; set; } = new EulerAngles();

    /// <summary>
    /// This field shall specify the dynamic changes to the entity's appearance attributes. This field shall be represented by an Entity Appearance record (see 6.2.26).
    /// </summary>
    public uint EntityAppearance { get; set; }

    /// <summary>
    /// This field shall specify the parameter values for each Variable Parameter record that is included (see 6.2.93 and Annex I).
    /// </summary>
    public List<VariableParameter> VariableParameters { get; set; } = [];

}

